package Project_Management.entity;
// Generated Mar 26, 2017 4:27:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Classes generated by hbm2java
 */
public class Classes  implements java.io.Serializable {


     private Integer classesId;
     private Faculty faculty;
     private boolean classesEnable;
     private String classesName;
     private int classesStudentCount;
     private String classesRepresentative;
     private String classesViceRepresentative;
     private String classesHeadTeacher;
     private int classesAcademicYear;
     private Set<Student> students = new HashSet<Student>(0);

    public Classes() {
    }

	
    public Classes(Faculty faculty, boolean classesEnable, String classesName, int classesStudentCount, String classesRepresentative, String classesViceRepresentative, String classesHeadTeacher, int classesAcademicYear) {
        this.faculty = faculty;
        this.classesEnable = classesEnable;
        this.classesName = classesName;
        this.classesStudentCount = classesStudentCount;
        this.classesRepresentative = classesRepresentative;
        this.classesViceRepresentative = classesViceRepresentative;
        this.classesHeadTeacher = classesHeadTeacher;
        this.classesAcademicYear = classesAcademicYear;
    }
    public Classes(Faculty faculty, boolean classesEnable, String classesName, int classesStudentCount, String classesRepresentative, String classesViceRepresentative, String classesHeadTeacher, int classesAcademicYear, Set<Student> students) {
       this.faculty = faculty;
       this.classesEnable = classesEnable;
       this.classesName = classesName;
       this.classesStudentCount = classesStudentCount;
       this.classesRepresentative = classesRepresentative;
       this.classesViceRepresentative = classesViceRepresentative;
       this.classesHeadTeacher = classesHeadTeacher;
       this.classesAcademicYear = classesAcademicYear;
       this.students = students;
    }
   
    public Integer getClassesId() {
        return this.classesId;
    }
    
    public void setClassesId(Integer classesId) {
        this.classesId = classesId;
    }
    public Faculty getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(Faculty faculty) {
        this.faculty = faculty;
    }
    public boolean isClassesEnable() {
        return this.classesEnable;
    }
    
    public void setClassesEnable(boolean classesEnable) {
        this.classesEnable = classesEnable;
    }
    public String getClassesName() {
        return this.classesName;
    }
    
    public void setClassesName(String classesName) {
        this.classesName = classesName;
    }
    public int getClassesStudentCount() {
        return this.classesStudentCount;
    }
    
    public void setClassesStudentCount(int classesStudentCount) {
        this.classesStudentCount = classesStudentCount;
    }
    public String getClassesRepresentative() {
        return this.classesRepresentative;
    }
    
    public void setClassesRepresentative(String classesRepresentative) {
        this.classesRepresentative = classesRepresentative;
    }
    public String getClassesViceRepresentative() {
        return this.classesViceRepresentative;
    }
    
    public void setClassesViceRepresentative(String classesViceRepresentative) {
        this.classesViceRepresentative = classesViceRepresentative;
    }
    public String getClassesHeadTeacher() {
        return this.classesHeadTeacher;
    }
    
    public void setClassesHeadTeacher(String classesHeadTeacher) {
        this.classesHeadTeacher = classesHeadTeacher;
    }
    public int getClassesAcademicYear() {
        return this.classesAcademicYear;
    }
    
    public void setClassesAcademicYear(int classesAcademicYear) {
        this.classesAcademicYear = classesAcademicYear;
    }
    public Set<Student> getStudents() {
        return this.students;
    }
    
    public void setStudents(Set<Student> students) {
        this.students = students;
    }




}


