package Project_Management.entity;
// Generated Mar 26, 2017 4:27:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Faculty generated by hbm2java
 */
public class Faculty  implements java.io.Serializable {


     private Integer facultyId;
     private boolean facultyEnable;
     private String facultyDean;
     private String facultyViceDean;
     private String facultyMajor;
     private int facultyLecturerCount;
     private int facultyStudentCount;
     private int facultyClassCount;
     private String facultySubjectList;
     private String facultyPersonnelManager;
     private Set<Classes> classeses = new HashSet<Classes>(0);
     private Set<User> users = new HashSet<User>(0);

    public Faculty() {
    }

	
    public Faculty(boolean facultyEnable, String facultyDean, String facultyViceDean, String facultyMajor, int facultyLecturerCount, int facultyStudentCount, int facultyClassCount, String facultySubjectList, String facultyPersonnelManager) {
        this.facultyEnable = facultyEnable;
        this.facultyDean = facultyDean;
        this.facultyViceDean = facultyViceDean;
        this.facultyMajor = facultyMajor;
        this.facultyLecturerCount = facultyLecturerCount;
        this.facultyStudentCount = facultyStudentCount;
        this.facultyClassCount = facultyClassCount;
        this.facultySubjectList = facultySubjectList;
        this.facultyPersonnelManager = facultyPersonnelManager;
    }
    public Faculty(boolean facultyEnable, String facultyDean, String facultyViceDean, String facultyMajor, int facultyLecturerCount, int facultyStudentCount, int facultyClassCount, String facultySubjectList, String facultyPersonnelManager, Set<Classes> classeses, Set<User> users) {
       this.facultyEnable = facultyEnable;
       this.facultyDean = facultyDean;
       this.facultyViceDean = facultyViceDean;
       this.facultyMajor = facultyMajor;
       this.facultyLecturerCount = facultyLecturerCount;
       this.facultyStudentCount = facultyStudentCount;
       this.facultyClassCount = facultyClassCount;
       this.facultySubjectList = facultySubjectList;
       this.facultyPersonnelManager = facultyPersonnelManager;
       this.classeses = classeses;
       this.users = users;
    }
   
    public Integer getFacultyId() {
        return this.facultyId;
    }
    
    public void setFacultyId(Integer facultyId) {
        this.facultyId = facultyId;
    }
    public boolean isFacultyEnable() {
        return this.facultyEnable;
    }
    
    public void setFacultyEnable(boolean facultyEnable) {
        this.facultyEnable = facultyEnable;
    }
    public String getFacultyDean() {
        return this.facultyDean;
    }
    
    public void setFacultyDean(String facultyDean) {
        this.facultyDean = facultyDean;
    }
    public String getFacultyViceDean() {
        return this.facultyViceDean;
    }
    
    public void setFacultyViceDean(String facultyViceDean) {
        this.facultyViceDean = facultyViceDean;
    }
    public String getFacultyMajor() {
        return this.facultyMajor;
    }
    
    public void setFacultyMajor(String facultyMajor) {
        this.facultyMajor = facultyMajor;
    }
    public int getFacultyLecturerCount() {
        return this.facultyLecturerCount;
    }
    
    public void setFacultyLecturerCount(int facultyLecturerCount) {
        this.facultyLecturerCount = facultyLecturerCount;
    }
    public int getFacultyStudentCount() {
        return this.facultyStudentCount;
    }
    
    public void setFacultyStudentCount(int facultyStudentCount) {
        this.facultyStudentCount = facultyStudentCount;
    }
    public int getFacultyClassCount() {
        return this.facultyClassCount;
    }
    
    public void setFacultyClassCount(int facultyClassCount) {
        this.facultyClassCount = facultyClassCount;
    }
    public String getFacultySubjectList() {
        return this.facultySubjectList;
    }
    
    public void setFacultySubjectList(String facultySubjectList) {
        this.facultySubjectList = facultySubjectList;
    }
    public String getFacultyPersonnelManager() {
        return this.facultyPersonnelManager;
    }
    
    public void setFacultyPersonnelManager(String facultyPersonnelManager) {
        this.facultyPersonnelManager = facultyPersonnelManager;
    }
    public Set<Classes> getClasseses() {
        return this.classeses;
    }
    
    public void setClasseses(Set<Classes> classeses) {
        this.classeses = classeses;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


