package Project_Management.entity;
// Generated Mar 26, 2017 4:27:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project  implements java.io.Serializable {


     private Integer projectId;
     private User userByProjectAuthorId;
     private User userByProjectInstructorId;
     private String projectName;
     private Float projectValuationPoint;
     private String projectAppraisal;
     private boolean projectEnable;
     private Date projectStartDate;
     private Date projectPostDate;
     private String projectBrief;
     private Integer projectViewCount;
     private Integer projectDownloadCount;
     private String projectFont;
     private String projectLanguage;
     private Float projectSize;
     private Integer projectPageCount;
     private Integer projectChapterCount;
     private Date projectLastModified;
     private String projectValuationCouncil;
     private String projectReviewerCouncil;
     private String projectNote;
     private String projectKeywork;
     private String projectTheme;
     private String projectTask;
     private Set<Comment> comments = new HashSet<Comment>(0);

    public Project() {
    }

	
    public Project(User userByProjectAuthorId, User userByProjectInstructorId, String projectName, boolean projectEnable) {
        this.userByProjectAuthorId = userByProjectAuthorId;
        this.userByProjectInstructorId = userByProjectInstructorId;
        this.projectName = projectName;
        this.projectEnable = projectEnable;
    }
    public Project(User userByProjectAuthorId, User userByProjectInstructorId, String projectName, Float projectValuationPoint, String projectAppraisal, boolean projectEnable, Date projectStartDate, Date projectPostDate, String projectBrief, Integer projectViewCount, Integer projectDownloadCount, String projectFont, String projectLanguage, Float projectSize, Integer projectPageCount, Integer projectChapterCount, Date projectLastModified, String projectValuationCouncil, String projectReviewerCouncil, String projectNote, String projectKeywork, String projectTheme, String projectTask, Set<Comment> comments) {
       this.userByProjectAuthorId = userByProjectAuthorId;
       this.userByProjectInstructorId = userByProjectInstructorId;
       this.projectName = projectName;
       this.projectValuationPoint = projectValuationPoint;
       this.projectAppraisal = projectAppraisal;
       this.projectEnable = projectEnable;
       this.projectStartDate = projectStartDate;
       this.projectPostDate = projectPostDate;
       this.projectBrief = projectBrief;
       this.projectViewCount = projectViewCount;
       this.projectDownloadCount = projectDownloadCount;
       this.projectFont = projectFont;
       this.projectLanguage = projectLanguage;
       this.projectSize = projectSize;
       this.projectPageCount = projectPageCount;
       this.projectChapterCount = projectChapterCount;
       this.projectLastModified = projectLastModified;
       this.projectValuationCouncil = projectValuationCouncil;
       this.projectReviewerCouncil = projectReviewerCouncil;
       this.projectNote = projectNote;
       this.projectKeywork = projectKeywork;
       this.projectTheme = projectTheme;
       this.projectTask = projectTask;
       this.comments = comments;
    }
   
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
    public User getUserByProjectAuthorId() {
        return this.userByProjectAuthorId;
    }
    
    public void setUserByProjectAuthorId(User userByProjectAuthorId) {
        this.userByProjectAuthorId = userByProjectAuthorId;
    }
    public User getUserByProjectInstructorId() {
        return this.userByProjectInstructorId;
    }
    
    public void setUserByProjectInstructorId(User userByProjectInstructorId) {
        this.userByProjectInstructorId = userByProjectInstructorId;
    }
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    public Float getProjectValuationPoint() {
        return this.projectValuationPoint;
    }
    
    public void setProjectValuationPoint(Float projectValuationPoint) {
        this.projectValuationPoint = projectValuationPoint;
    }
    public String getProjectAppraisal() {
        return this.projectAppraisal;
    }
    
    public void setProjectAppraisal(String projectAppraisal) {
        this.projectAppraisal = projectAppraisal;
    }
    public boolean isProjectEnable() {
        return this.projectEnable;
    }
    
    public void setProjectEnable(boolean projectEnable) {
        this.projectEnable = projectEnable;
    }
    public Date getProjectStartDate() {
        return this.projectStartDate;
    }
    
    public void setProjectStartDate(Date projectStartDate) {
        this.projectStartDate = projectStartDate;
    }
    public Date getProjectPostDate() {
        return this.projectPostDate;
    }
    
    public void setProjectPostDate(Date projectPostDate) {
        this.projectPostDate = projectPostDate;
    }
    public String getProjectBrief() {
        return this.projectBrief;
    }
    
    public void setProjectBrief(String projectBrief) {
        this.projectBrief = projectBrief;
    }
    public Integer getProjectViewCount() {
        return this.projectViewCount;
    }
    
    public void setProjectViewCount(Integer projectViewCount) {
        this.projectViewCount = projectViewCount;
    }
    public Integer getProjectDownloadCount() {
        return this.projectDownloadCount;
    }
    
    public void setProjectDownloadCount(Integer projectDownloadCount) {
        this.projectDownloadCount = projectDownloadCount;
    }
    public String getProjectFont() {
        return this.projectFont;
    }
    
    public void setProjectFont(String projectFont) {
        this.projectFont = projectFont;
    }
    public String getProjectLanguage() {
        return this.projectLanguage;
    }
    
    public void setProjectLanguage(String projectLanguage) {
        this.projectLanguage = projectLanguage;
    }
    public Float getProjectSize() {
        return this.projectSize;
    }
    
    public void setProjectSize(Float projectSize) {
        this.projectSize = projectSize;
    }
    public Integer getProjectPageCount() {
        return this.projectPageCount;
    }
    
    public void setProjectPageCount(Integer projectPageCount) {
        this.projectPageCount = projectPageCount;
    }
    public Integer getProjectChapterCount() {
        return this.projectChapterCount;
    }
    
    public void setProjectChapterCount(Integer projectChapterCount) {
        this.projectChapterCount = projectChapterCount;
    }
    public Date getProjectLastModified() {
        return this.projectLastModified;
    }
    
    public void setProjectLastModified(Date projectLastModified) {
        this.projectLastModified = projectLastModified;
    }
    public String getProjectValuationCouncil() {
        return this.projectValuationCouncil;
    }
    
    public void setProjectValuationCouncil(String projectValuationCouncil) {
        this.projectValuationCouncil = projectValuationCouncil;
    }
    public String getProjectReviewerCouncil() {
        return this.projectReviewerCouncil;
    }
    
    public void setProjectReviewerCouncil(String projectReviewerCouncil) {
        this.projectReviewerCouncil = projectReviewerCouncil;
    }
    public String getProjectNote() {
        return this.projectNote;
    }
    
    public void setProjectNote(String projectNote) {
        this.projectNote = projectNote;
    }
    public String getProjectKeywork() {
        return this.projectKeywork;
    }
    
    public void setProjectKeywork(String projectKeywork) {
        this.projectKeywork = projectKeywork;
    }
    public String getProjectTheme() {
        return this.projectTheme;
    }
    
    public void setProjectTheme(String projectTheme) {
        this.projectTheme = projectTheme;
    }
    public String getProjectTask() {
        return this.projectTask;
    }
    
    public void setProjectTask(String projectTask) {
        this.projectTask = projectTask;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }




}


