package Project_Management.entity;
// Generated Mar 26, 2017 4:27:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private Faculty faculty;
     private String userName;
     private Date userDateOfBirth;
     private String userGender;
     private String userIdentificationNumber;
     private String userLanguage;
     private Integer userSalary;
     private String userAddress;
     private String userHometown;
     private String userMobileNumber;
     private String userPhoneNumber;
     private String userReligion;
     private String userEthnic;
     private Date userAccountCreateDate;
     private Date userLastLogin;
     private Date userLastModified;
     private String userAlias;
     private String userPassword;
     private String userAvatar;
     private boolean userEnable;
     private boolean userActive;
     private String userFacebook;
     private String userEmail;
     private String userDuty;
     private String userAuthority;
     private String userSelfDescribe;
     private String userDiploma;
     private String userDegree;
     private String userMarriageStatus;
     private Integer userManagerParentId;
     private Set<Comment> comments = new HashSet<Comment>(0);
     private Set<Project> projectsForProjectAuthorId = new HashSet<Project>(0);
     private Set<Project> projectsForProjectInstructorId = new HashSet<Project>(0);
     private Student student;

    public User() {
    }

	
    public User(Faculty faculty, String userName, Date userDateOfBirth, String userGender, String userIdentificationNumber, String userLanguage, Date userAccountCreateDate, String userAlias, String userPassword, String userAvatar, boolean userEnable, boolean userActive, String userDuty, String userAuthority) {
        this.faculty = faculty;
        this.userName = userName;
        this.userDateOfBirth = userDateOfBirth;
        this.userGender = userGender;
        this.userIdentificationNumber = userIdentificationNumber;
        this.userLanguage = userLanguage;
        this.userAccountCreateDate = userAccountCreateDate;
        this.userAlias = userAlias;
        this.userPassword = userPassword;
        this.userAvatar = userAvatar;
        this.userEnable = userEnable;
        this.userActive = userActive;
        this.userDuty = userDuty;
        this.userAuthority = userAuthority;
    }
    public User(Faculty faculty, String userName, Date userDateOfBirth, String userGender, String userIdentificationNumber, String userLanguage, Integer userSalary, String userAddress, String userHometown, String userMobileNumber, String userPhoneNumber, String userReligion, String userEthnic, Date userAccountCreateDate, Date userLastLogin, Date userLastModified, String userAlias, String userPassword, String userAvatar, boolean userEnable, boolean userActive, String userFacebook, String userEmail, String userDuty, String userAuthority, String userSelfDescribe, String userDiploma, String userDegree, String userMarriageStatus, Integer userManagerParentId, Set<Comment> comments, Set<Project> projectsForProjectAuthorId, Set<Project> projectsForProjectInstructorId, Student student) {
       this.faculty = faculty;
       this.userName = userName;
       this.userDateOfBirth = userDateOfBirth;
       this.userGender = userGender;
       this.userIdentificationNumber = userIdentificationNumber;
       this.userLanguage = userLanguage;
       this.userSalary = userSalary;
       this.userAddress = userAddress;
       this.userHometown = userHometown;
       this.userMobileNumber = userMobileNumber;
       this.userPhoneNumber = userPhoneNumber;
       this.userReligion = userReligion;
       this.userEthnic = userEthnic;
       this.userAccountCreateDate = userAccountCreateDate;
       this.userLastLogin = userLastLogin;
       this.userLastModified = userLastModified;
       this.userAlias = userAlias;
       this.userPassword = userPassword;
       this.userAvatar = userAvatar;
       this.userEnable = userEnable;
       this.userActive = userActive;
       this.userFacebook = userFacebook;
       this.userEmail = userEmail;
       this.userDuty = userDuty;
       this.userAuthority = userAuthority;
       this.userSelfDescribe = userSelfDescribe;
       this.userDiploma = userDiploma;
       this.userDegree = userDegree;
       this.userMarriageStatus = userMarriageStatus;
       this.userManagerParentId = userManagerParentId;
       this.comments = comments;
       this.projectsForProjectAuthorId = projectsForProjectAuthorId;
       this.projectsForProjectInstructorId = projectsForProjectInstructorId;
       this.student = student;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Faculty getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(Faculty faculty) {
        this.faculty = faculty;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public Date getUserDateOfBirth() {
        return this.userDateOfBirth;
    }
    
    public void setUserDateOfBirth(Date userDateOfBirth) {
        this.userDateOfBirth = userDateOfBirth;
    }
    public String getUserGender() {
        return this.userGender;
    }
    
    public void setUserGender(String userGender) {
        this.userGender = userGender;
    }
    public String getUserIdentificationNumber() {
        return this.userIdentificationNumber;
    }
    
    public void setUserIdentificationNumber(String userIdentificationNumber) {
        this.userIdentificationNumber = userIdentificationNumber;
    }
    public String getUserLanguage() {
        return this.userLanguage;
    }
    
    public void setUserLanguage(String userLanguage) {
        this.userLanguage = userLanguage;
    }
    public Integer getUserSalary() {
        return this.userSalary;
    }
    
    public void setUserSalary(Integer userSalary) {
        this.userSalary = userSalary;
    }
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }
    public String getUserHometown() {
        return this.userHometown;
    }
    
    public void setUserHometown(String userHometown) {
        this.userHometown = userHometown;
    }
    public String getUserMobileNumber() {
        return this.userMobileNumber;
    }
    
    public void setUserMobileNumber(String userMobileNumber) {
        this.userMobileNumber = userMobileNumber;
    }
    public String getUserPhoneNumber() {
        return this.userPhoneNumber;
    }
    
    public void setUserPhoneNumber(String userPhoneNumber) {
        this.userPhoneNumber = userPhoneNumber;
    }
    public String getUserReligion() {
        return this.userReligion;
    }
    
    public void setUserReligion(String userReligion) {
        this.userReligion = userReligion;
    }
    public String getUserEthnic() {
        return this.userEthnic;
    }
    
    public void setUserEthnic(String userEthnic) {
        this.userEthnic = userEthnic;
    }
    public Date getUserAccountCreateDate() {
        return this.userAccountCreateDate;
    }
    
    public void setUserAccountCreateDate(Date userAccountCreateDate) {
        this.userAccountCreateDate = userAccountCreateDate;
    }
    public Date getUserLastLogin() {
        return this.userLastLogin;
    }
    
    public void setUserLastLogin(Date userLastLogin) {
        this.userLastLogin = userLastLogin;
    }
    public Date getUserLastModified() {
        return this.userLastModified;
    }
    
    public void setUserLastModified(Date userLastModified) {
        this.userLastModified = userLastModified;
    }
    public String getUserAlias() {
        return this.userAlias;
    }
    
    public void setUserAlias(String userAlias) {
        this.userAlias = userAlias;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserAvatar() {
        return this.userAvatar;
    }
    
    public void setUserAvatar(String userAvatar) {
        this.userAvatar = userAvatar;
    }
    public boolean isUserEnable() {
        return this.userEnable;
    }
    
    public void setUserEnable(boolean userEnable) {
        this.userEnable = userEnable;
    }
    public boolean isUserActive() {
        return this.userActive;
    }
    
    public void setUserActive(boolean userActive) {
        this.userActive = userActive;
    }
    public String getUserFacebook() {
        return this.userFacebook;
    }
    
    public void setUserFacebook(String userFacebook) {
        this.userFacebook = userFacebook;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getUserDuty() {
        return this.userDuty;
    }
    
    public void setUserDuty(String userDuty) {
        this.userDuty = userDuty;
    }
    public String getUserAuthority() {
        return this.userAuthority;
    }
    
    public void setUserAuthority(String userAuthority) {
        this.userAuthority = userAuthority;
    }
    public String getUserSelfDescribe() {
        return this.userSelfDescribe;
    }
    
    public void setUserSelfDescribe(String userSelfDescribe) {
        this.userSelfDescribe = userSelfDescribe;
    }
    public String getUserDiploma() {
        return this.userDiploma;
    }
    
    public void setUserDiploma(String userDiploma) {
        this.userDiploma = userDiploma;
    }
    public String getUserDegree() {
        return this.userDegree;
    }
    
    public void setUserDegree(String userDegree) {
        this.userDegree = userDegree;
    }
    public String getUserMarriageStatus() {
        return this.userMarriageStatus;
    }
    
    public void setUserMarriageStatus(String userMarriageStatus) {
        this.userMarriageStatus = userMarriageStatus;
    }
    public Integer getUserManagerParentId() {
        return this.userManagerParentId;
    }
    
    public void setUserManagerParentId(Integer userManagerParentId) {
        this.userManagerParentId = userManagerParentId;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }
    public Set<Project> getProjectsForProjectAuthorId() {
        return this.projectsForProjectAuthorId;
    }
    
    public void setProjectsForProjectAuthorId(Set<Project> projectsForProjectAuthorId) {
        this.projectsForProjectAuthorId = projectsForProjectAuthorId;
    }
    public Set<Project> getProjectsForProjectInstructorId() {
        return this.projectsForProjectInstructorId;
    }
    
    public void setProjectsForProjectInstructorId(Set<Project> projectsForProjectInstructorId) {
        this.projectsForProjectInstructorId = projectsForProjectInstructorId;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }




}


